#  For full config options, check the docs:
#    docs.serverless.com

service: schedule-function

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  region: ap-northeast-1
  stackName: ${self:service}

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  hello:
    handler: bin/hello
    name: hello
    description: schedule function
    events:
      - schedule:
          rate: cron(0/1 * * * ? *)
          enabled: true
          inputTransformer:
            inputPathsMap:
              eventTime: '$.time'
            inputTemplate: '{"time": <eventTime>, "key1": "value1"}'

resources:
  Description: >
    Schedule Function Stack with Serverless Framework from golang

